Add the contact form
AndresEspi/portafolio pull request #3
Opened 2023-06-12 21:26 UTC by AndresEspi

achievements

- Add the "footer" element before the closing "body" tag.

- Inside the "footer" element, add a "section" element.

- Inside the "section" element of the footer, add an "h2" element with the class "titleFooter" and the desired text.

- Next, within the same "section" element, add a "form" element with the empty action (action="") and the class "form".

- Inside the "form" element, add the following elements:

- An "input" element with class "form-list" of type "text" and attributes "placeholder" for full name, "required" and "maxlength" set to 30.

- An "input" element with the class "form-list" of type "email" and the attribute "placeholder" for the email address, and also "required".

- A "textarea" element with class "form-textarea" and attributes "placeholder" for writing a message, "maxlength" set to 500, and "required".

- A "button" element with the class "button" and the text "Get in touch".

- After the closing "/form" element, add another "section" element inside the "footer".

- Inside the second "section" of the footer, add an "ul" element with the class "icons1".

- Inside the "ul" element, add five "li" elements, each with an "a" element inside.

- Inside each "a" element, add an "img" element with the class "icon1" and the path of the corresponding image.

2023-06-13 14:41 UTC, AbelG101 reviewed
![](https://media.giphy.com/media/PkFYci8BUkmdA7K1qa/giphy.gif)

# Hi @AndresEspi 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Please take note that this is a pair-programming activity which means each team member needs to have a substantial contribution to the project. So please reach out to your team members and have them add some commits.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-13 20:11 UTC, Ofarouq310 requested changes
Hi @AndresEspi, @montsecruz9 & @Drod86 , ✋

Good job so far! 💪 
There are some issues that you still need to work on to go to the next project but you are almost there! 🥈 

![giphy](https://github.com/AndresEspi/portafolio/assets/102612396/d3185292-b9b2-43a2-93c7-8a66b1e983a0)

## Highlights
✅ Descriptive PR title & summary.
✅ Good commit messages.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 20:11 UTC, Ofarouq310 commented on index.html
> +                <button class="botn">Get in touch</button>
- [ ] Kindly note that your `form` has to collect data by using the [Formspree service](https://formspree.io/html).
   -  `Form` uses the action and method attribute to integrate with [formspree service](https://formspree.io/html).
      * `action` value should be similar to `https://formspree.io/f/{form_id}`, you get the `id` from `Formspree`.
      * `method` value equals `POST`.

```suggestion
            </h2>
            <form class="form" action="https://formspree.io/f/{form_id}" method="post">
                <input class="form-list" type="text" placeholder="Full Name" required maxlength="30">
                <input class="form-list" type="email" placeholder="Email Address" required>
                <textarea class="form-textarea" placeholder="Write me something..." maxlength="500" required></textarea>    
                <button class="botn">Get in touch</button>
```

2023-06-13 20:11 UTC, Ofarouq310 commented on index.html
> +                <button class="botn">Get in touch</button>
- [ ] Kindly make sure to implement the button interactions required in this project.
  
  ![image](https://github.com/AndresEspi/portafolio/assets/102612396/66cbd785-d812-48f6-a2e9-34207a0bb426)

2023-06-14 23:57 UTC, Felix45 requested changes
Hi @AndresEspi , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif" width="350px" />

 ## Highlights :heavy_check_mark: 
- [x] Implemented button interactions correctly :white_check_mark: 
- [x] Added `action` and `method` attributes to the contact form correctly :white_check_mark:   


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 23:57 UTC, Felix45 commented on index.html
> +                <textarea class="form-textarea" placeholder="Write me something..." maxlength="500" required></textarea>
- [ Required ] Good job implementing some of the changes from the previous reviewer, however, after adding the `action` and `method` attributes to your form the submission to `formspree` gives an error. This is because the form `input` and `textarea` elements don't have their corresponding `name` attributes, please see the screenshot below and rectify this error.

## Screenshot
![Screenshot from 2023-06-15 02-46-40](https://github.com/AndresEspi/portafolio/assets/16392046/6fb83cdf-65aa-4535-ae58-dacaf85f26e4)

## Example code 
```HTML
<form class="form" action="https://formspree.io/f/mjvdngwj" method="post">
   <input class="form-list" name="username" type="text" placeholder="Full Name" required maxlength="30">
  <input class="form-list" type="email" name="emailaddress" placeholder="Email Address" required>
 <textarea class="form-textarea"  name="message" placeholder="Write me something..." maxlength="500" required> 
 </textarea>    
<button class="botn">Get in touch</button>
</form>

```

2023-06-15 02:48 UTC, franclobo approved these changes
Hi @AndresEspi, 

# STATUS: APPROVED 😃 

![git-merge](https://github.com/AndresEspi/portafolio/assets/58642949/d03254b0-5609-4e3d-872f-c5539c52aa46)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Descriptive PR ✔️
- Correct Github flow ✔️
- Correct use of POST method ✔️
- Form works as expected ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 03:02 UTC, merged